apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: timeoff-managment
  name: timeoff-managment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timeoff-managment
  template:
    metadata:
      labels:
        app: timeoff-managment
    spec:
      containers:
      - command:
        - sh
        - -c
        - npm start
        env:
        - name: VERSION
          value: ${RELEASE_VERSION}
        image: 447335552551.dkr.ecr.us-east-1.amazonaws.com/demo-timeoff:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        name: demo-timeoff
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /db
          name: db-config-vol
      initContainers:
      - command:  ["sh", "-c", "/app/timeoff-management/node_modules/.bin/sequelize", "db:migrate", "--config", "/db/db.json", "--models-path", "lib/model/db"]
        env:
        - name: VERSION
          value: ${RELEASE_VERSION}
        - name: NODE_ENV
          value: production
        ports:
        - containerPort: 3002
          protocol: TCP
        image: 447335552551.dkr.ecr.us-east-1.amazonaws.com/demo-timeoff:${IMAGE_TAG}
        imagePullPolicy: Always
        name: demo-timeoff-migrations
        volumeMounts:
        - mountPath: /db
          name: db-config-vol
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
      volumes:
      - name: db-config-vol
        secret:
          secretName: topsecrets