apiVersion: v1
kind: Service
metadata:
  labels:
    app: timeoff-managment
  name: timeoff-managment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: timeoff-managment
  sessionAffinity: None
  type: LoadBalancer
        # For HA set type LoadBalancer