name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Update and Install sqlite3
      run: sudo apt update -y && sudo apt install sqlite3 -y  
    - uses: actions/checkout@v3
    - name: Clone Project
      run: git clone https://github.com/timeoff-management/timeoff-management-application.git $PWD/timeoff-management
    - name: Build the Docker image
      run: cd  $PWD/timeoff-management && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
